//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases all of the units stats by 15, including max health and attack..
        /// </summary>
        internal static string AbilitiesDescriptionAnyAscend {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionAnyAscend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heals the target for 100% of the casters level..
        /// </summary>
        internal static string AbilitiesDescriptionAnyBattleRegeneration {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionAnyBattleRegeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal damage equal to 315% of the units attack..
        /// </summary>
        internal static string AbilitiesDescriptionAnyDoubleSwing {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionAnyDoubleSwing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase the highest stat of the target by 20% of the casters highest stat..
        /// </summary>
        internal static string AbilitiesDescriptionAnyEmpowerment {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionAnyEmpowerment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase the maximum health of the target by 20% of the casters highest stat..
        /// </summary>
        internal static string AbilitiesDescriptionAnyInvigorate {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionAnyInvigorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal damage to the target for 100% of the units attack..
        /// </summary>
        internal static string AbilitiesDescriptionAnyMeleeAttack {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionAnyMeleeAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases a random of your targets stats by 50%..
        /// </summary>
        internal static string AbilitiesDescriptionAnyOpportunity {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionAnyOpportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals all of the units stats combined in damage..
        /// </summary>
        internal static string AbilitiesDescriptionAnyTotalitarism {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionAnyTotalitarism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the strength and agility of the Caretaker by 20%..
        /// </summary>
        internal static string AbilitiesDescriptionCaretakerAction {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionCaretakerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 25% of the Caretakers maximum health in damage to the target..
        /// </summary>
        internal static string AbilitiesDescriptionCaretakerBodySlam {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionCaretakerBodySlam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splits the Caretakers health deficit as healing between all allies..
        /// </summary>
        internal static string AbilitiesDescriptionCaretakerDeathdefiance {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionCaretakerDeathdefiance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Caretaker heals a target ally to full, but takes the allys&apos; health deficit in damage..
        /// </summary>
        internal static string AbilitiesDescriptionCaretakerLifeblood {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionCaretakerLifeblood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 90% of the Caretakers health deficit in damage to the target AND the Caretaker..
        /// </summary>
        internal static string AbilitiesDescriptionCaretakerLifeforce {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionCaretakerLifeforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 125% of the Caretakers combined Strength and Agility to the target..
        /// </summary>
        internal static string AbilitiesDescriptionCaretakerPowerAndDexterity {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionCaretakerPowerAndDexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 55% of the Caretakers Agility in damage, but takes damage equal to the difference between Strength and Agility..
        /// </summary>
        internal static string AbilitiesDescriptionCaretakerSacrifice {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionCaretakerSacrifice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heals target ally for 75% of the Caretakers strength, but injures himself for 50% of the amount healed..
        /// </summary>
        internal static string AbilitiesDescriptionCaretakerZealOfHumanity {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionCaretakerZealOfHumanity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the target allys&apos; highest stat by 40%.
        /// </summary>
        internal static string AbilitiesDescriptionPaladinBlessing {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionPaladinBlessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heals the target for 75% of their maximum health, but decreases their maximum health by 20%..
        /// </summary>
        internal static string AbilitiesDescriptionPaladinDesperatePlea {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionPaladinDesperatePlea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 40% of the Paladins strength in damage and heals him for 30% of his intellect..
        /// </summary>
        internal static string AbilitiesDescriptionPaladinJustice {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionPaladinJustice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the strength and intellect of the Paladin by 20%..
        /// </summary>
        internal static string AbilitiesDescriptionPaladinPrayer {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionPaladinPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Paladin heals the target for 25% of his combined strength and intellect..
        /// </summary>
        internal static string AbilitiesDescriptionPaladinRaiseSpirit {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionPaladinRaiseSpirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heals a random ally and deals damage to the target for 40% of the Paladins intellect..
        /// </summary>
        internal static string AbilitiesDescriptionPaladinSerenity {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionPaladinSerenity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heals the paladin to full health, but reduces all his stats by 10%..
        /// </summary>
        internal static string AbilitiesDescriptionPaladinThePowerOfFaith {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionPaladinThePowerOfFaith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 50% of the Paladins strength in damage..
        /// </summary>
        internal static string AbilitiesDescriptionPaladinWrath {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionPaladinWrath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals damage for 55% of the Synergists Agility, but subtracts the difference between Agility and Intellect from the damage..
        /// </summary>
        internal static string AbilitiesDescriptionSynergistAgileMind {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionSynergistAgileMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the intellect and agility of the Synergist by 20%..
        /// </summary>
        internal static string AbilitiesDescriptionSynergistAlign {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionSynergistAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of Agility and Intellect, increases lowest stat by 15% and highest by 10%..
        /// </summary>
        internal static string AbilitiesDescriptionSynergistBalance {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionSynergistBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heals all allies for 50/37/25 % of the Synergists Intellect, but reduces intellect by 20%..
        /// </summary>
        internal static string AbilitiesDescriptionSynergistCollapsedEquality {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionSynergistCollapsedEquality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligns all allies health to be at the average percentage and heals them for 8% of the Synergists agility and intellect..
        /// </summary>
        internal static string AbilitiesDescriptionSynergistCompleteBalance {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionSynergistCompleteBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 25% of the Synergists combined intellect and agility in damage..
        /// </summary>
        internal static string AbilitiesDescriptionSynergistDuality {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionSynergistDuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 115% of the Synergists Intellect in damage, subtracting the difference between Intellect and Agility..
        /// </summary>
        internal static string AbilitiesDescriptionSynergistMentalAgility {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionSynergistMentalAgility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 145% of the Synergists combined intellect and agility as damage, but subtracts difference between them from this amount..
        /// </summary>
        internal static string AbilitiesDescriptionSynergistSynergy {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionSynergistSynergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 100% of the Thiefs agility in damage and heals him for 10% of the damage dealt..
        /// </summary>
        internal static string AbilitiesDescriptionThiefBloodstealer {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionThiefBloodstealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Thief uses the best attack of his allies together with his own, dealing 65% of their combined damage..
        /// </summary>
        internal static string AbilitiesDescriptionThiefBorrowWeapon {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionThiefBorrowWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 250% of the Thiefs agility and 40% of his Attack as damage to the target..
        /// </summary>
        internal static string AbilitiesDescriptionThiefDirtyTricks {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionThiefDirtyTricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the attack of the Thief by 50%..
        /// </summary>
        internal static string AbilitiesDescriptionThiefEnvenom {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionThiefEnvenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 10% of the Thiefs Attack to the target, 10% of his agility times..
        /// </summary>
        internal static string AbilitiesDescriptionThiefFlurry {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionThiefFlurry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 140% of the Thiefs Attack and 75% of his Agility in damage..
        /// </summary>
        internal static string AbilitiesDescriptionThiefPoisonedBlade {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionThiefPoisonedBlade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiftly injure the target for 50% of the casters agility..
        /// </summary>
        internal static string AbilitiesDescriptionThiefQuickAttack {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionThiefQuickAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the agility of the Thief by 40%.
        /// </summary>
        internal static string AbilitiesDescriptionThiefSwiftness {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionThiefSwiftness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals anywhere between 175 and 75% of the Warriors strength in damage..
        /// </summary>
        internal static string AbilitiesDescriptionWarriorBlindRage {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionWarriorBlindRage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 750% attack damage if the target dies from this. Otherwise, deals 150% Weapon Damage..
        /// </summary>
        internal static string AbilitiesDescriptionWarriorExecution {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionWarriorExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the Warriors attack by 25% of the Warriors health deficit..
        /// </summary>
        internal static string AbilitiesDescriptionWarriorInfuriate {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionWarriorInfuriate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Warrior deals 350% of his strength in damage to the target, but injures of his allies for 15% of the damage dealt..
        /// </summary>
        internal static string AbilitiesDescriptionWarriorInsanity {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionWarriorInsanity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal damage to the target based on 90% attack damage and 10% of the Warriors strength..
        /// </summary>
        internal static string AbilitiesDescriptionWarriorPowerStrike {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionWarriorPowerStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Warriors deals 150% of his  strength in damage, but takes 10% damage of the damage himself..
        /// </summary>
        internal static string AbilitiesDescriptionWarriorRampage {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionWarriorRampage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the strength of the Warrior by 40%..
        /// </summary>
        internal static string AbilitiesDescriptionWarriorRoar {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionWarriorRoar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal damage to the target based on the 50% of the strength of the Warrior..
        /// </summary>
        internal static string AbilitiesDescriptionWarriorStrength {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionWarriorStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduces maximum health by 60%, but increases intellect by 300%..
        /// </summary>
        internal static string AbilitiesDescriptionWizardArchon {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionWizardArchon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the intellect of the Wizard by 40%..
        /// </summary>
        internal static string AbilitiesDescriptionWizardBrilliance {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionWizardBrilliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ability deals damage to the target, based on 50% of the casters intellect..
        /// </summary>
        internal static string AbilitiesDescriptionWizardFireball {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionWizardFireball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals damage to the target for 110% of the Wizards intellect..
        /// </summary>
        internal static string AbilitiesDescriptionWizardFlameComet {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionWizardFlameComet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ability heals the target player for 25% of the casters Intellect..
        /// </summary>
        internal static string AbilitiesDescriptionWizardHeal {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionWizardHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals damage to the target for 280% of the Wizards intellect..
        /// </summary>
        internal static string AbilitiesDescriptionWizardInferno {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionWizardInferno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heals all allies for 55/40/30 % of the Wizards Intellect. Percentage is dependant on number of valid targets..
        /// </summary>
        internal static string AbilitiesDescriptionWizardOracle {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionWizardOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Wizard heals the target for 50% of her intellect..
        /// </summary>
        internal static string AbilitiesDescriptionWizardRevitalize {
            get {
                return ResourceManager.GetString("AbilitiesDescriptionWizardRevitalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascend.
        /// </summary>
        internal static string AbilitiesTitleAnyAscend {
            get {
                return ResourceManager.GetString("AbilitiesTitleAnyAscend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle Regeneration.
        /// </summary>
        internal static string AbilitiesTitleAnyBattleRegeneration {
            get {
                return ResourceManager.GetString("AbilitiesTitleAnyBattleRegeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Swing.
        /// </summary>
        internal static string AbilitiesTitleAnyDoubleSwing {
            get {
                return ResourceManager.GetString("AbilitiesTitleAnyDoubleSwing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empowerment.
        /// </summary>
        internal static string AbilitiesTitleAnyEmpowerment {
            get {
                return ResourceManager.GetString("AbilitiesTitleAnyEmpowerment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invigorate.
        /// </summary>
        internal static string AbilitiesTitleAnyInvigorate {
            get {
                return ResourceManager.GetString("AbilitiesTitleAnyInvigorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee Attack.
        /// </summary>
        internal static string AbilitiesTitleAnyMeleeAttack {
            get {
                return ResourceManager.GetString("AbilitiesTitleAnyMeleeAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity.
        /// </summary>
        internal static string AbilitiesTitleAnyOpportunity {
            get {
                return ResourceManager.GetString("AbilitiesTitleAnyOpportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totalitarism.
        /// </summary>
        internal static string AbilitiesTitleAnyTotalitarism {
            get {
                return ResourceManager.GetString("AbilitiesTitleAnyTotalitarism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string AbilitiesTitleCaretakerAction {
            get {
                return ResourceManager.GetString("AbilitiesTitleCaretakerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Slam.
        /// </summary>
        internal static string AbilitiesTitleCaretakerBodySlam {
            get {
                return ResourceManager.GetString("AbilitiesTitleCaretakerBodySlam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deathdefiance.
        /// </summary>
        internal static string AbilitiesTitleCaretakerDeathdefiance {
            get {
                return ResourceManager.GetString("AbilitiesTitleCaretakerDeathdefiance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifeblood.
        /// </summary>
        internal static string AbilitiesTitleCaretakerLifeblood {
            get {
                return ResourceManager.GetString("AbilitiesTitleCaretakerLifeblood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifeforce.
        /// </summary>
        internal static string AbilitiesTitleCaretakerLifeforce {
            get {
                return ResourceManager.GetString("AbilitiesTitleCaretakerLifeforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power And Dexterity.
        /// </summary>
        internal static string AbilitiesTitleCaretakerPowerAndDexterity {
            get {
                return ResourceManager.GetString("AbilitiesTitleCaretakerPowerAndDexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacrifice.
        /// </summary>
        internal static string AbilitiesTitleCaretakerSacrifice {
            get {
                return ResourceManager.GetString("AbilitiesTitleCaretakerSacrifice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfHumanity.
        /// </summary>
        internal static string AbilitiesTitleCaretakerZealOfHumanity {
            get {
                return ResourceManager.GetString("AbilitiesTitleCaretakerZealOfHumanity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blessing.
        /// </summary>
        internal static string AbilitiesTitlePaladinBlessing {
            get {
                return ResourceManager.GetString("AbilitiesTitlePaladinBlessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desperate Plea.
        /// </summary>
        internal static string AbilitiesTitlePaladinDesperatePlea {
            get {
                return ResourceManager.GetString("AbilitiesTitlePaladinDesperatePlea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justice.
        /// </summary>
        internal static string AbilitiesTitlePaladinJustice {
            get {
                return ResourceManager.GetString("AbilitiesTitlePaladinJustice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prayer.
        /// </summary>
        internal static string AbilitiesTitlePaladinPrayer {
            get {
                return ResourceManager.GetString("AbilitiesTitlePaladinPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Spirit.
        /// </summary>
        internal static string AbilitiesTitlePaladinRaiseSpirit {
            get {
                return ResourceManager.GetString("AbilitiesTitlePaladinRaiseSpirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladin Serenity.
        /// </summary>
        internal static string AbilitiesTitlePaladinSerenity {
            get {
                return ResourceManager.GetString("AbilitiesTitlePaladinSerenity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Power Of Faith.
        /// </summary>
        internal static string AbilitiesTitlePaladinThePowerOfFaith {
            get {
                return ResourceManager.GetString("AbilitiesTitlePaladinThePowerOfFaith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrath.
        /// </summary>
        internal static string AbilitiesTitlePaladinWrath {
            get {
                return ResourceManager.GetString("AbilitiesTitlePaladinWrath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agile Mind.
        /// </summary>
        internal static string AbilitiesTitleSynergistAgileMind {
            get {
                return ResourceManager.GetString("AbilitiesTitleSynergistAgileMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align.
        /// </summary>
        internal static string AbilitiesTitleSynergistAlign {
            get {
                return ResourceManager.GetString("AbilitiesTitleSynergistAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string AbilitiesTitleSynergistBalance {
            get {
                return ResourceManager.GetString("AbilitiesTitleSynergistBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapsed Equality.
        /// </summary>
        internal static string AbilitiesTitleSynergistCollapsedEquality {
            get {
                return ResourceManager.GetString("AbilitiesTitleSynergistCollapsedEquality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Balance.
        /// </summary>
        internal static string AbilitiesTitleSynergistCompleteBalance {
            get {
                return ResourceManager.GetString("AbilitiesTitleSynergistCompleteBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duality.
        /// </summary>
        internal static string AbilitiesTitleSynergistDuality {
            get {
                return ResourceManager.GetString("AbilitiesTitleSynergistDuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mental Agility.
        /// </summary>
        internal static string AbilitiesTitleSynergistMentalAgility {
            get {
                return ResourceManager.GetString("AbilitiesTitleSynergistMentalAgility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synergy.
        /// </summary>
        internal static string AbilitiesTitleSynergistSynergy {
            get {
                return ResourceManager.GetString("AbilitiesTitleSynergistSynergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloodstealer.
        /// </summary>
        internal static string AbilitiesTitleThiefBloodstealer {
            get {
                return ResourceManager.GetString("AbilitiesTitleThiefBloodstealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow Weapon.
        /// </summary>
        internal static string AbilitiesTitleThiefBorrowWeapon {
            get {
                return ResourceManager.GetString("AbilitiesTitleThiefBorrowWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirty Tricks.
        /// </summary>
        internal static string AbilitiesTitleThiefDirtyTricks {
            get {
                return ResourceManager.GetString("AbilitiesTitleThiefDirtyTricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envenom.
        /// </summary>
        internal static string AbilitiesTitleThiefEnvenom {
            get {
                return ResourceManager.GetString("AbilitiesTitleThiefEnvenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flurry.
        /// </summary>
        internal static string AbilitiesTitleThiefFlurry {
            get {
                return ResourceManager.GetString("AbilitiesTitleThiefFlurry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poisoned Blade.
        /// </summary>
        internal static string AbilitiesTitleThiefPoisonedBlade {
            get {
                return ResourceManager.GetString("AbilitiesTitleThiefPoisonedBlade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Attack.
        /// </summary>
        internal static string AbilitiesTitleThiefQuickAttack {
            get {
                return ResourceManager.GetString("AbilitiesTitleThiefQuickAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiftness.
        /// </summary>
        internal static string AbilitiesTitleThiefSwiftness {
            get {
                return ResourceManager.GetString("AbilitiesTitleThiefSwiftness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blind Rage.
        /// </summary>
        internal static string AbilitiesTitleWarriorBlindRage {
            get {
                return ResourceManager.GetString("AbilitiesTitleWarriorBlindRage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution.
        /// </summary>
        internal static string AbilitiesTitleWarriorExecution {
            get {
                return ResourceManager.GetString("AbilitiesTitleWarriorExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infuriate.
        /// </summary>
        internal static string AbilitiesTitleWarriorInfuriate {
            get {
                return ResourceManager.GetString("AbilitiesTitleWarriorInfuriate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insanity.
        /// </summary>
        internal static string AbilitiesTitleWarriorInsanity {
            get {
                return ResourceManager.GetString("AbilitiesTitleWarriorInsanity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Strike.
        /// </summary>
        internal static string AbilitiesTitleWarriorPowerStrike {
            get {
                return ResourceManager.GetString("AbilitiesTitleWarriorPowerStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rampage.
        /// </summary>
        internal static string AbilitiesTitleWarriorRampage {
            get {
                return ResourceManager.GetString("AbilitiesTitleWarriorRampage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roar.
        /// </summary>
        internal static string AbilitiesTitleWarriorRoar {
            get {
                return ResourceManager.GetString("AbilitiesTitleWarriorRoar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string AbilitiesTitleWarriorStrength {
            get {
                return ResourceManager.GetString("AbilitiesTitleWarriorStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archon.
        /// </summary>
        internal static string AbilitiesTitleWizardArchon {
            get {
                return ResourceManager.GetString("AbilitiesTitleWizardArchon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brilliance.
        /// </summary>
        internal static string AbilitiesTitleWizardBrilliance {
            get {
                return ResourceManager.GetString("AbilitiesTitleWizardBrilliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireball.
        /// </summary>
        internal static string AbilitiesTitleWizardFireball {
            get {
                return ResourceManager.GetString("AbilitiesTitleWizardFireball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flame Comet.
        /// </summary>
        internal static string AbilitiesTitleWizardFlameComet {
            get {
                return ResourceManager.GetString("AbilitiesTitleWizardFlameComet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal.
        /// </summary>
        internal static string AbilitiesTitleWizardHeal {
            get {
                return ResourceManager.GetString("AbilitiesTitleWizardHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inferno.
        /// </summary>
        internal static string AbilitiesTitleWizardInferno {
            get {
                return ResourceManager.GetString("AbilitiesTitleWizardInferno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle.
        /// </summary>
        internal static string AbilitiesTitleWizardOracle {
            get {
                return ResourceManager.GetString("AbilitiesTitleWizardOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revitalize.
        /// </summary>
        internal static string AbilitiesTitleWizardRevitalize {
            get {
                return ResourceManager.GetString("AbilitiesTitleWizardRevitalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowLeft {
            get {
                object obj = ResourceManager.GetObject("arrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowRight {
            get {
                object obj = ResourceManager.GetObject("arrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Axe,Axe,Double Axe,Military Axe,War Axe,Large Axe,Broad Axe,Battle Axe,Great Axe,Giant Axe.
        /// </summary>
        internal static string AxesNames {
            get {
                return ResourceManager.GetString("AxesNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream backmusic1 {
            get {
                return ResourceManager.GetStream("backmusic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream backmusic2 {
            get {
                return ResourceManager.GetStream("backmusic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap beast {
            get {
                object obj = ResourceManager.GetObject("beast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bodyslam {
            get {
                object obj = ResourceManager.GetObject("bodyslam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spider Bow,Blade Bow,Shadow Bow,Great Bow,Diamond Bow,Crusader Bow,Ward Bow,Hydra Bow,Short Bow,Hunter&apos;s Bow,Long Bow,Composite Bow,Short Battle Bow,Long Battle Bow,Short War Bow,Long War Bow.
        /// </summary>
        internal static string BowNames {
            get {
                return ResourceManager.GetString("BowNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream buttonpress {
            get {
                return ResourceManager.GetStream("buttonpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caretaker {
            get {
                object obj = ResourceManager.GetObject("caretaker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 0.1.4.7 (20/02-2014):
        ///
        ///	- General:
        ///		- The game was named! It is now called:
        ///
        ///					The Legend of Eiwar!
        ///
        ///		- A new game mode was added! You can now play with multiple of your characters against the computer!
        ///		- The UI has not be rewamped completely, but certain elements have been significantly improved!
        ///		- You can now see how much Dust an item would give if disenchanted and how much dust you have now.
        ///		- The bug with text being out of place has been fixed.
        ///		- Fixed a bug where the gam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dusk Shroud,Wyrmhide,Scarab Husk,Wire Fleece,Diamond Mail,Loricated Mail,Great Hauberk,Boneweave,Balrog Skin,Archon Plate,Kraken Shell,Hellforge Plate,Lacquered Plate,Shadow Plate,Sacred Armor,Ghost Armor,Serpentskin Armor,Demonhide Armor,Trellised Armor,Linked Mail,Tigulated Mail,Cuirass,Mesh Armor,Russet Armor,Mage Plate,Sharktooth Armor,Templar Coat,Embossed Plate,Chaos Armor,Ornate Plate,Quilted Armor,Leather Armor,Hard Leather Armor,Studded Leather,Ring Mail,Scale Mail,Breast Plate,Chain Mail,Splint Ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChestArmorNames {
            get {
                return ResourceManager.GetString("ChestArmorNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bone Knife,Mithril Point,Fanged Knife,Legend Spike,Poignard,Rondel,Cinquedeas,Stiletto,Dagger,Dirk,Kris,Blade.
        /// </summary>
        internal static string DaggerNames {
            get {
                return ResourceManager.GetString("DaggerNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A protector of the weak, he deals damage and heals based on his health. His abilities are based on Strength, Agility and Health..
        /// </summary>
        internal static string DescriptionCaretaker {
            get {
                return ResourceManager.GetString("DescriptionCaretaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A crusader of the church, he focuses on healing while dealing damage. His abilities are based on Strength and Intellect..
        /// </summary>
        internal static string DescriptionPaladin {
            get {
                return ResourceManager.GetString("DescriptionPaladin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cunning and agile equilibrium, she always seeks to perfect balance between stats to deal devasteting damage to enemies. Her abilities are based on Agility and Intellect..
        /// </summary>
        internal static string DescriptionSynergist {
            get {
                return ResourceManager.GetString("DescriptionSynergist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working in a shadows, the Thief deales damage with his quickness and &apos;&apos;borrows&apos;&apos; equipment from his allies. His abilities are based on Agility and Attack..
        /// </summary>
        internal static string DescriptionThief {
            get {
                return ResourceManager.GetString("DescriptionThief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A torrent of fury, dealing uncontrollable damage to whatever is around him. His abilities are based on Strength and Attack..
        /// </summary>
        internal static string DescriptionWarrior {
            get {
                return ResourceManager.GetString("DescriptionWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An enigma of power, who deals great amounts of magical damage or heals grivieus wounds. Her abilities are based on Intellect..
        /// </summary>
        internal static string DescriptionWizard {
            get {
                return ResourceManager.GetString("DescriptionWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dragon {
            get {
                object obj = ResourceManager.GetObject("dragon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap duality {
            get {
                object obj = ResourceManager.GetObject("duality", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fireball {
            get {
                object obj = ResourceManager.GetObject("fireball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shako,Hydraskull,Armet,Giant Conch,Spired Helm,Demonhead,Corona,Bone Visage,War Hat,Sallet,Casque,Basinet,Winged Helm,Death Mask,Grand Crown,Grim Helm,Cap,Skull Cap,Helm,Full Helm,Great Helm,Mask,Crown,Bone Helm.
        /// </summary>
        internal static string HeadArmorNames {
            get {
                return ResourceManager.GetString("HeadArmorNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heal {
            get {
                object obj = ResourceManager.GetObject("heal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap humanoid {
            get {
                object obj = ResourceManager.GetObject("humanoid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloth Pants,Leather Pants,Hide Breeches,Chain Leggings,Faulds,Plate Leggings,Legwraps,Etched Pants,Chausses,Tassets,Boneweave Faulds,Leg Guards,Poleyns,Warlord Leg Plates,Schynbalds,Sovereign Tassets,Archon Fauld.
        /// </summary>
        internal static string LegArmorNames {
            get {
                return ResourceManager.GetString("LegArmorNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club,Spiked Club,Mace,Morning Star,Flail,War Hammer,Maul,Truncheon,Tyrant Club,Reinforced Mace,Devil Star,Scourge,Legendary Mallet,Ogre Maul,Thunder Maul.
        /// </summary>
        internal static string MaxeNames {
            get {
                return ResourceManager.GetString("MaxeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap meleeattack {
            get {
                object obj = ResourceManager.GetObject("meleeattack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paladin {
            get {
                object obj = ResourceManager.GetObject("paladin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Pericl {
            get {
                object obj = ResourceManager.GetObject("Pericl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strengthening,Agile,Dextrous,Sturdy,Acrobatic,Systematic,Precise,Acute,Relentless,Coordinated,Warding,Artist&apos;s,Construct&apos;s,Myrmidon&apos;s,Aegis,Duelist&apos;s,Flurry,Pugilist&apos;s,Honest,Lancer&apos;s,Eschewing,Cunning,Bolstering,Brilliant,Intelligent,Stalwart,Diplomatic,Calm,Omniscient,Formation,Reformation,Solid,Survivor&apos;s,Ravaging,Condeming,Vital,Sagacity,Guardian,Harmonizing,Physician&apos;s,Ameliorating,Bastion&apos;s,Barricade,Friendly,Hospitable,Generous,Altruistic,Aversion,Deterrant,Indomitable,Intimidating,Clever,Finessed,Eg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prefixes {
            get {
                return ResourceManager.GetString("Prefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap questionmark {
            get {
                object obj = ResourceManager.GetObject("questionmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quickattack {
            get {
                object obj = ResourceManager.GetObject("quickattack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking Stick,Stalagmite,Elder Staff,Shillelagh,Archon Staff,Jo Staff,Quarterstaff,Cedar Staff,Gothic Staff,Rune Staf,Short Staff,Long Staff,Gnarled Staff,Battle Staff
        ///War Staff.
        /// </summary>
        internal static string StaffNames {
            get {
                return ResourceManager.GetString("StaffNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap strength {
            get {
                object obj = ResourceManager.GetObject("strength", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of Worth,of Measure,of Excellence,of Performance,of Transcendence,of Perfection,of the Giant,of the Colossus,of Craftmanship,of Storms,of Defiance,of Equilibrium,of Amicae,of the Guard,of Ages,of Calm,of Accuracy,of Precision,of the Sniper,of the Marksman,of the Deadeye,of the Ranger,of the Assassin,of Shining,of Light,of Radiance,of Ease,of Mastery,of Grandmastery,of Skill,of Renown,of Acclaim,of Fame,of Infamy,of Celebration,of the Clouds,of the Sky,of the Meteor,of the Comet,of the Heavens,of the Galaxy, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Suffixes {
            get {
                return ResourceManager.GetString("Suffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Sword,Scimitar,Sabre,Falchion,Crystal Sword,Broad Sword,Long Sword,War Sword,Two-handed Sword,Claymore,Giant Sword,Bastard Sword,Flamberge.
        /// </summary>
        internal static string SwordNames {
            get {
                return ResourceManager.GetString("SwordNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap synergist {
            get {
                object obj = ResourceManager.GetObject("synergist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thief {
            get {
                object obj = ResourceManager.GetObject("thief", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap undead {
            get {
                object obj = ResourceManager.GetObject("undead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tab presents planned changes to the game, that has not yet been implemented. Please note that these changes are not certain to go through.
        ///
        ///	- Finish up the support tab with facts about the game and instructions on how to play.
        ///
        ///	- Use the last &quot;Support&quot; button to  open the webpage for bug reporting.
        ///
        ///	- Add &quot;Zones&quot; where the player can battle in.
        ///
        ///	- I have an idea of how to save data on the server, rendering local copies useless.
        ///		- Simply name each .xml file after the user and check that t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Upcomming {
            get {
                return ResourceManager.GetString("Upcomming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warrior {
            get {
                object obj = ResourceManager.GetObject("warrior", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wizard {
            get {
                object obj = ResourceManager.GetObject("wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wrath {
            get {
                object obj = ResourceManager.GetObject("wrath", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
