//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowLeft {
            get {
                object obj = ResourceManager.GetObject("arrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowRight {
            get {
                object obj = ResourceManager.GetObject("arrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Axe,Axe,Double Axe,Military Axe,War Axe,Large Axe,Broad Axe,Battle Axe,Great Axe,Giant Axe.
        /// </summary>
        internal static string AxesNames {
            get {
                return ResourceManager.GetString("AxesNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream backmusic1 {
            get {
                return ResourceManager.GetStream("backmusic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream backmusic2 {
            get {
                return ResourceManager.GetStream("backmusic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap beast {
            get {
                object obj = ResourceManager.GetObject("beast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bodyslam {
            get {
                object obj = ResourceManager.GetObject("bodyslam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spider Bow,Blade Bow,Shadow Bow,Great Bow,Diamond Bow,Crusader Bow,Ward Bow,Hydra Bow,Short Bow,Hunter&apos;s Bow,Long Bow,Composite Bow,Short Battle Bow,Long Battle Bow,Short War Bow,Long War Bow.
        /// </summary>
        internal static string BowNames {
            get {
                return ResourceManager.GetString("BowNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream buttonpress {
            get {
                return ResourceManager.GetStream("buttonpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caretaker {
            get {
                object obj = ResourceManager.GetObject("caretaker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 0.1.3.10 (4/11-2013):
        ///
        ///	- General:
        ///		- Added background temporary background music. There are current some issues with sound 
        ///		  and animations, so only background music is implemented. To read more about the issues,
        ///		  see the &apos;&apos;Upcomming&apos;&apos; tab.
        ///		- Updated the &apos;&apos;How to Play&apos;&apos; section in the Support menu to include a description of quests
        ///		  and the new attribute, Speed.
        ///		- Added many, many more prefixes and suffixes for items.
        ///		- Made sure the player never receive two pieces of loot  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dusk Shroud,Wyrmhide,Scarab Husk,Wire Fleece,Diamond Mail,Loricated Mail,Great Hauberk,Boneweave,Balrog Skin,Archon Plate,Kraken Shell,Hellforge Plate,Lacquered Plate,Shadow Plate,Sacred Armor,Ghost Armor,Serpentskin Armor,Demonhide Armor,Trellised Armor,Linked Mail,Tigulated Mail,Cuirass,Mesh Armor,Russet Armor,Mage Plate,Sharktooth Armor,Templar Coat,Embossed Plate,Chaos Armor,Ornate Plate,Quilted Armor,Leather Armor,Hard Leather Armor,Studded Leather,Ring Mail,Scale Mail,Breast Plate,Chain Mail,Splint Ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChestArmorNames {
            get {
                return ResourceManager.GetString("ChestArmorNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bone Knife,Mithril Point,Fanged Knife,Legend Spike,Poignard,Rondel,Cinquedeas,Stiletto,Dagger,Dirk,Kris,Blade.
        /// </summary>
        internal static string DaggerNames {
            get {
                return ResourceManager.GetString("DaggerNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dragon {
            get {
                object obj = ResourceManager.GetObject("dragon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap duality {
            get {
                object obj = ResourceManager.GetObject("duality", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fireball {
            get {
                object obj = ResourceManager.GetObject("fireball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shako,Hydraskull,Armet,Giant Conch,Spired Helm,Demonhead,Corona,Bone Visage,War Hat,Sallet,Casque,Basinet,Winged Helm,Death Mask,Grand Crown,Grim Helm,Cap,Skull Cap,Helm,Full Helm,Great Helm,Mask,Crown,Bone Helm.
        /// </summary>
        internal static string HeadArmorNames {
            get {
                return ResourceManager.GetString("HeadArmorNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heal {
            get {
                object obj = ResourceManager.GetObject("heal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap humanoid {
            get {
                object obj = ResourceManager.GetObject("humanoid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloth Pants,Leather Pants,Hide Breeches,Chain Leggings,Faulds,Plate Leggings,Legwraps,Etched Pants,Chausses,Tassets,Boneweave Faulds,Leg Guards,Poleyns,Warlord Leg Plates,Schynbalds,Sovereign Tassets,Archon Fauld.
        /// </summary>
        internal static string LegArmorNames {
            get {
                return ResourceManager.GetString("LegArmorNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club,Spiked Club,Mace,Morning Star,Flail,War Hammer,Maul,Truncheon,Tyrant Club,Reinforced Mace,Devil Star,Scourge,Legendary Mallet,Ogre Maul,Thunder Maul.
        /// </summary>
        internal static string MaxeNames {
            get {
                return ResourceManager.GetString("MaxeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap meleeattack {
            get {
                object obj = ResourceManager.GetObject("meleeattack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paladin {
            get {
                object obj = ResourceManager.GetObject("paladin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Pericl {
            get {
                object obj = ResourceManager.GetObject("Pericl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strengthening,Agile,Dextrous,Sturdy,Acrobatic,Systematic,Precise,Acute,Relentless,Coordinated,Warding,Artist&apos;s,Construct&apos;s,Myrmidon&apos;s,Aegis,Duelist&apos;s,Flurry,Pugilist&apos;s,Honest,Lancer&apos;s,Eschewing,Cunning,Bolstering,Brilliant,Intelligent,Stalwart,Diplomatic,Calm,Omniscient,Formation,Reformation,Solid,Survivor&apos;s,Ravaging,Condeming,Vital,Sagacity,Guardian,Harmonizing,Physician&apos;s,Ameliorating,Bastion&apos;s,Barricade,Friendly,Hospitable,Generous,Altruistic,Aversion,Deterrant,Indomitable,Intimidating,Clever,Finessed,Eg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prefixes {
            get {
                return ResourceManager.GetString("Prefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap questionmark {
            get {
                object obj = ResourceManager.GetObject("questionmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quickattack {
            get {
                object obj = ResourceManager.GetObject("quickattack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking Stick,Stalagmite,Elder Staff,Shillelagh,Archon Staff,Jo Staff,Quarterstaff,Cedar Staff,Gothic Staff,Rune Staf,Short Staff,Long Staff,Gnarled Staff,Battle Staff
        ///War Staff.
        /// </summary>
        internal static string StaffNames {
            get {
                return ResourceManager.GetString("StaffNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap strength {
            get {
                object obj = ResourceManager.GetObject("strength", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of Worth,of Measure,of Excellence,of Performance,of Transcendence,of Perfection,of the Giant,of the Colossus,of Craftmanship,of Storms,of Defiance,of Equilibrium,of Amicae,of the Guard,of Ages,of Calm,of Accuracy,of Precision,of the Sniper,of the Marksman,of the Deadeye,of the Ranger,of the Assassin,of Shining,of Light,of Radiance,of Ease,of Mastery,of Grandmastery,of Skill,of Renown,of Acclaim,of Fame,of Infamy,of Celebration,of the Clouds,of the Sky,of the Meteor,of the Comet,of the Heavens,of the Galaxy, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Suffixes {
            get {
                return ResourceManager.GetString("Suffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Sword,Scimitar,Sabre,Falchion,Crystal Sword,Broad Sword,Long Sword,War Sword,Two-handed Sword,Claymore,Giant Sword,Bastard Sword,Flamberge.
        /// </summary>
        internal static string SwordNames {
            get {
                return ResourceManager.GetString("SwordNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap synergist {
            get {
                object obj = ResourceManager.GetObject("synergist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thief {
            get {
                object obj = ResourceManager.GetObject("thief", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap undead {
            get {
                object obj = ResourceManager.GetObject("undead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tab presents planned changes to the game, that has not yet been implemented. Please note that these changes are not certain to go through.
        ///
        ///	- Finish up the support tab with facts about the game and instructions on how to play.
        ///
        ///	- I have an idea of how to save data on the server, rendering local copies useless.
        ///		- Simply name each .xml file after the user and check that there&apos;s only 1 of 
        ///		  that user name. Then save these files in a &apos;&apos;Data&apos;&apos; folder on the server.
        ///
        ///	- Fix bugs and balance cl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Upcomming {
            get {
                return ResourceManager.GetString("Upcomming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warrior {
            get {
                object obj = ResourceManager.GetObject("warrior", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wizard {
            get {
                object obj = ResourceManager.GetObject("wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wrath {
            get {
                object obj = ResourceManager.GetObject("wrath", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
